/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { useControls } from 'leva'

export default function Terasa(props) {
  const { nodes, materials } = useGLTF("/static/terasa_merge.glb");

  const dusumea = useControls('Dusumea', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const treapta = useControls('Treapta', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const scara = useControls('Structura metalica scara', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const profil60 = useControls('Structura metalica 60x40', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const profilI = useControls('Structura metalica profil I', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const manaCurenta = useControls('Mana curenta - platbanda 35x10', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const stinghii = useControls('Stinghii - Fi12', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const montanti = useControls('Montanti - profil T35', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })
  const traverse = useControls('Traverse + stalpi', {visible: true, opacity: {value: 1,min: 0,max: 1,step: 0.05} })

  console.log(materials)

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.profil_I.geometry}
        visible={profilI.visible}
      ><meshStandardMaterial color={materials.Gri.color} opacity={profilI.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.profil_60x40.geometry}
        rotation={[0, 0, -Math.PI / 2]}
        visible={profil60.visible}
      ><meshStandardMaterial color={materials.Gri.color} opacity={profil60.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Traverse_+_stalpi"].geometry}
        visible={traverse.visible}
      ><meshStandardMaterial color={materials.Gri.color} opacity={traverse.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
      <group position={[1.99, -0.44, 1.27]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          visible={scara.visible}
        ><meshStandardMaterial color={materials.Gri.color} opacity={scara.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_1.geometry}
          visible={treapta.visible}
        ><meshStandardMaterial color={materials.Dusumea.color} opacity={treapta.opacity} roughness={0.7} transparent/></mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dusumea_3900x145x19.geometry}
        visible={dusumea.visible}
      ><meshStandardMaterial color={materials.Dusumea.color} opacity={dusumea.opacity} roughness={0.7} transparent/></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Montant_T35_+_talpa"].geometry}
        visible={montanti.visible}
      ><meshStandardMaterial color={materials.Gri.color} opacity={montanti.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Platbanda_35x10.geometry}
        visible={manaCurenta.visible}
      ><meshStandardMaterial color={materials.Gri.color} opacity={manaCurenta.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stinghii_Fi12.geometry}
        visible={stinghii.visible}
      ><meshStandardMaterial color={materials.Gri.color} opacity={stinghii.opacity} roughness={materials.Gri.roughness} metalness transparent/></mesh>
    </group>
  );
}

useGLTF.preload("/static/terasa_merge.glb");
